### Homework 5: Pandas Practice

For this homework, you'll be using Pandas to analyze a database of fatal police shootings in the US.

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("data/fatal-police-shootings-data.csv",
                   parse_dates=["date"])

In [21]:
data.dtypes

id                                     int64
date                          datetime64[us]
threat_type                              str
flee_status                              str
armed_with                               str
city                                     str
county                                   str
state                                    str
latitude                             float64
longitude                            float64
location_precision                       str
name                                     str
age                                  float64
gender                                   str
race                                     str
race_source                              str
was_mental_illness_related              bool
body_camera                             bool
agency_ids                               str
poc                                     bool
dtype: object

In [8]:
data.head()

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids
0,3,2015-01-02,point,not,gun,Shelton,Mason,WA,47.246826,-123.121592,not_available,Tim Elliot,53.0,male,A,not_available,True,False,73
1,4,2015-01-02,point,not,gun,Aloha,Washington,OR,45.487421,-122.891696,not_available,Lewis Lee Lembke,47.0,male,W,not_available,False,False,70
2,5,2015-01-03,move,not,unarmed,Wichita,Sedgwick,KS,37.694766,-97.280554,not_available,John Paul Quintero,23.0,male,H,not_available,False,False,238
3,8,2015-01-04,point,not,replica,San Francisco,San Francisco,CA,37.762910,-122.422001,not_available,Matthew Hoffman,32.0,male,W,not_available,True,False,196
4,9,2015-01-04,point,not,other,Evans,Weld,CO,40.383937,-104.692261,not_available,Michael Rodriguez,39.0,male,H,not_available,False,False,473

Spend some time examining the columns in the data to get a little familiar with the information you're working with...

In [9]:
len(data)

10430

In [10]:
# What is the time range of the available data? Use a line of pandas code to find out. 
data["date"].describe()

count                         10430
mean     2020-03-06 05:37:25.599233
min             2015-01-02 00:00:00
25%             2017-08-25 00:00:00
50%             2020-04-12 00:00:00
75%             2022-10-02 00:00:00
max             2024-12-31 00:00:00
Name: date, dtype: object

In [ ]:
# Say you want to analyze the racial disparities in this dataset, broken down by race and by the larger category of non-white people. 
# Write a line of code that takes a look at the universe of values in the race column.
data["race"].value_counts()

race
W        4659
B        2486
H        1717
A         184
N         146
O          37
W;B         4
W;H         3
B;H         3
W;B;N       1
N;H         1
W;A         1
Name: count, dtype: int64

In [ ]:
# Make the letters in the race column all lower-case
data["race"] = data["race"].str.lower()

In [ ]:
# Create a new column called "poc" and use a lambda function to set it equal to True or False based on the information in the race column.
data["poc"] = data["race"].apply(lambda x: "w" == x)

# How many rows are POC and how many are White?
data["poc"].value_counts()

poc
False    5771
True     4659
Name: count, dtype: int64

In [6]:
# I want to know which county had the most police killings but some counties in the U.S. have the same name. 
# Create a column called country_state and populate it with the county and the state to create unique pairs. 
data["county_state"] = data["county"] + ", " + data["state"]

# Now answer the question: which county had the most killings?
data["county_state"].value_counts()

county_state
Los Angeles, CA       222
Maricopa, AZ          151
Harris, TX             96
San Bernardino, CA     79
Bexar, TX              64
                     ...
Lee, NC                 1
St. Francis, AR         1
Amador, CA              1
Crosby, TX              1
Rolette, ND             1
Name: count, Length: 1401, dtype: int64

In [7]:
data["armed_with"].value_counts()

armed_with
gun                          6040
knife                        1776
unarmed                       565
undetermined                  463
vehicle                       372
replica                       331
blunt_object                  252
unknown                       165
other                         108
gun;knife                      42
gun;vehicle                    39
vehicle;gun                    25
knife;knife                     6
knife;blunt_object              5
other;gun                       4
blunt_object;blunt_object       4
blunt_object;knife              3
knife;vehicle                   3
vehicle;knife                   3
gun;other                       2
knife;replica                   2
replica;vehicle                 1
vehicle;knife;other             1
replica;knife                   1
other;blunt_object;knife        1
other;knife                     1
blunt_object;other              1
knife;unknown                   1
replica;blunt_object            1
blunt_object;gun                1
Name: count, dtype: int64

In [8]:
# Create a new column called "unarmed" and use a lambda function to set it to True/False based on the relevant info.

data["unarmed"] = data["armed_with"].apply(lambda x: "unarmed" == x)
data["unarmed"].value_counts()

# Create a subset of the data for unarmed killings and store it in a new variable called unarmed_killings. 
unarmed_killings = data[data["unarmed"] == True]

# Which county had the most of these?
unarmed_killings["county_state"].value_counts()

county_state
Los Angeles, CA    19
Orange, CA          7
Maricopa, AZ        6
Harris, TX          6
San Diego, CA       6
                   ..
Orange, TX          1
Whitfield, GA       1
Charlotte, FL       1
Montgomery, TX      1
Crosby, TX          1
Name: count, Length: 219, dtype: int64

In [9]:
# We could have done that more smoothly using a groupby. So let's do that. 
# Group the original dataset by your new columns unarmed killings and county_state. 
# Use loc[] to isolate the rows where unarmed==True
# Sort from highest #killings to lowest


data.groupby(
    ["unarmed", "county_state"]
).size().loc[True].sort_values(ascending=False)

county_state
Los Angeles, CA       19
Orange, CA             7
Maricopa, AZ           6
San Bernardino, CA     6
San Diego, CA          6
                      ..
Hancock, OH            1
Hartford, CT           1
Hawaii, HI             1
Henderson, TN          1
Laurel, KY             1
Length: 219, dtype: int64

I want to examine the data by race and gender to understand whether Black women are disproportionately killed by the police compared to white women and by how much. I'm not going to tell you what to do beyond that — this is where you need to think creatively as a data reporter! What information do you need to look up to figure out this answer? Go step by step and show your working using Python comments.

In [ ]:
data["gender"].value_counts()

#88 rows
# data[ (data["gender"] == "female") & (data["race"] == "b")] 
# scale by 21 million
print(88/21)

#254 rows
# data[ (data["gender"] == "female") & (data["race"] == "w")] 
# scale by 100 million
print(254/101)

# Black women are killed at nearly twice the rate of white women in the U.S.

4.190476190476191
2.514851485148515

Your editor wants you to examine mental illness in police killings in the US by state. Seeing which state had the most killings of mentally ill people is not enough; you'll need to scale by population. To do that, you will use the Python census library to access Census data. You'll need an API key to use it.

Sign up for a Census API key at this website: https://api.census.gov/data/key_signup.html 

Then check your email to get the API key. Make sure to click the activation link in the email.

In [ ]:
# install the python census library.
%pip install census
%pip install geonamescache

### TAKE A BREAK!

It can take several minutes for your API key to be activated. Go have a stretch, get some water, etc...

In [10]:
api_key = "0010829a29be4463d1d26faa503662db44bd0aa3"

In [11]:
import os
from census import Census
from us import states
import geonamescache

In [17]:
gc = geonamescache.GeonamesCache()
us_states = gc.get_us_states()

# The geonamescache library stores the fips code for each state. 
# Adjust the loop I have below to populate the empty dictionary below, 
# where the keys are state codes (i.e. AK) and the values are fips codes (as strings)

state_to_fips = {}


for state_code, state_info in us_states.items():
    state_to_fips[state_info["code"]] = state_info["fips"]

print(state_to_fips)

{'AK': '02', 'AL': '01', 'AR': '05', 'AZ': '04', 'CA': '06', 'CO': '08', 'CT': '09', 'DC': '11', 'DE': '10', 'FL': '12', 'GA': '13', 'HI': '15', 'IA': '19', 'ID': '16', 'IL': '17', 'IN': '18', 'KS': '20', 'KY': '21', 'LA': '22', 'MA': '25', 'MD': '24', 'ME': '23', 'MI': '26', 'MN': '27', 'MO': '29', 'MS': '28', 'MT': '30', 'NC': '37', 'ND': '38', 'NE': '31', 'NH': '33', 'NJ': '34', 'NM': '35', 'NV': '32', 'NY': '36', 'OH': '39', 'OK': '40', 'OR': '41', 'PA': '42', 'RI': '44', 'SC': '45', 'SD': '46', 'TN': '47', 'TX': '48', 'UT': '49', 'VA': '51', 'VT': '50', 'WA': '53', 'WI': '55', 'WV': '54', 'WY': '56'}

In [18]:
# Ping the Census API with your key...
c = Census(api_key, year=2023)

# We're using American Community Survey Version 5 (acs5 in the census library)
# Population is represented by data code "B01003_001E"
# So to pull the population for New York state, which is FIPS code 36, here's what you do:

ny_population_query = c.acs5.state(("NAME", "B01003_001E"), "36" )
print(ny_population_query)

# Examine the results of the query. Looks like the Census API hands back a list with a dictionary in it, 
# and you have to pull the population info out of that...

[{'NAME': 'New York', 'B01003_001E': 19872319.0, 'state': '36'}]

In [30]:
print(f"The population of New York is: {ny_population_query[0]["B01003_001E"]}")

The population of New York is: 19872319.0

In [19]:
# OK now use the state_to_fips dictionary you made in conjunction with the census API to create one more dictionary
# where keys are the state code and values are the population

# This might take a while to run! You're pinging an API 50 times. 

state_population = {}

for state_code in state_to_fips.keys():
    fips = state_to_fips[state_code]
    population_query = c.acs5.state(("NAME", "B01003_001E"),  fips)
    population = population_query[0]["B01003_001E"]
    state_population[state_code] = population

In [45]:
print(state_population)

{'AK': 733971.0, 'AL': 5054253.0, 'AR': 3032651.0, 'AZ': 7268175.0, 'CA': 39242785.0, 'CO': 5810774.0, 'CT': 3598348.0, 'DC': 672079.0, 'DE': 1005872.0, 'FL': 21928881.0, 'GA': 10822590.0, 'HI': 1445635.0, 'IA': 3195937.0, 'ID': 1893296.0, 'IL': 12692653.0, 'IN': 6811752.0, 'KS': 2937569.0, 'KY': 4510725.0, 'LA': 4621025.0, 'MA': 6992395.0, 'MD': 6170738.0, 'ME': 1377400.0, 'MI': 10051595.0, 'MN': 5713716.0, 'MO': 6168181.0, 'MS': 2951438.0, 'MT': 1105072.0, 'NC': 10584340.0, 'ND': 779361.0, 'NE': 1965926.0, 'NH': 1387834.0, 'NJ': 9267014.0, 'NM': 2114768.0, 'NV': 3141000.0, 'NY': 19872319.0, 'OH': 11780046.0, 'OK': 3995260.0, 'OR': 4238714.0, 'PA': 12986518.0, 'RI': 1095371.0, 'SC': 5212774.0, 'SD': 899194.0, 'TN': 6986082.0, 'TX': 29640343.0, 'UT': 3331187.0, 'VA': 8657499.0, 'VT': 645254.0, 'WA': 7740984.0, 'WI': 5892023.0, 'WV': 1784462.0, 'WY': 579761.0}

I want you to learn to use the Census API because, chances are, it will be useful data to merge/explore as you work on your projects. 

OK. Now back to our data on police shootings. Use pandas and the census library to figure out which state has the highest rate of police killings of disabled people. There isn't one way to get the answer! Think creatively.

In [20]:
disabled_killings = data[data["was_mental_illness_related"]==True]
len(disabled_killings)

disabled_per_state = disabled_killings["state"].value_counts().reset_index()
disabled_per_state

   state  count
0     CA    274
1     TX    168
2     FL    166
3     OH     72
4     WA     70
5     AZ     70
6     NC     64
7     GA     63
8     NY     63
9     TN     61
10    PA     52
11    OK     51
12    MI     49
13    IN     49
14    CO     47
15    OR     44
16    VA     43
17    AL     42
18    MO     42
19    WI     38
20    NV     37
21    LA     36
22    IL     35
23    NM     35
24    MD     34
25    SC     30
26    MN     29
27    UT     29
28    NJ     22
29    KY     20
30    AR     20
31    KS     20
32    MA     19
33    MS     17
34    WV     16
35    NH     14
36    SD     12
37    IA     12
38    ID     12
39    NE     11
40    AK     10
41    MT      9
42    ME      8
43    HI      8
44    WY      6
45    CT      6
46    VT      6
47    ND      6
48    DC      5
49    DE      4
50    RI      1

In [22]:
disabled_per_state["state_population"] = disabled_per_state["state"].apply(lambda x: state_population[x])

In [24]:
disabled_per_state.dtypes

state                   str
count                 int64
state_population    float64
dtype: object

In [ ]:
disabled_per_state.columns = disabled_per_state.columns.str.strip()

In [63]:
disabled_per_state["disabled_killing_rate"] = disabled_per_state.apply(
    lambda row: row["count"]/row["state_population"]*100000,
    axis=1
)

In [66]:
disabled_per_state.sort_values(
    by="disabled_killing_rate",
    ascending=False
)

   state  count  state_population  disabled_killing_rate
23    NM     35         2114768.0               1.655028
40    AK     10          733971.0               1.362452
36    SD     12          899194.0               1.334528
11    OK     51         3995260.0               1.276513
20    NV     37         3141000.0               1.177969
15    OR     44         4238714.0               1.038051
44    WY      6          579761.0               1.034909
35    NH     14         1387834.0               1.008766
5     AZ     70         7268175.0               0.963103
46    VT      6          645254.0               0.929866
4     WA     70         7740984.0               0.904278
34    WV     16         1784462.0               0.896629
9     TN     61         6986082.0               0.873165
27    UT     29         3331187.0               0.870561
17    AL     42         5054253.0               0.830983
41    MT      9         1105072.0               0.814427
14    CO     47         5810774.0               0.808842
21    LA     36         4621025.0               0.779048
47    ND      6          779361.0               0.769861
2     FL    166        21928881.0               0.756993
48    DC      5          672079.0               0.743960
13    IN     49         6811752.0               0.719345
0     CA    274        39242785.0               0.698218
18    MO     42         6168181.0               0.680914
31    KS     20         2937569.0               0.680835
30    AR     20         3032651.0               0.659489
19    WI     38         5892023.0               0.644940
38    ID     12         1893296.0               0.633815
3     OH     72        11780046.0               0.611203
6     NC     64        10584340.0               0.604667
7     GA     63        10822590.0               0.582116
42    ME      8         1377400.0               0.580804
33    MS     17         2951438.0               0.575990
25    SC     30         5212774.0               0.575509
1     TX    168        29640343.0               0.566795
39    NE     11         1965926.0               0.559533
43    HI      8         1445635.0               0.553390
24    MD     34         6170738.0               0.550988
26    MN     29         5713716.0               0.507551
16    VA     43         8657499.0               0.496679
12    MI     49        10051595.0               0.487485
29    KY     20         4510725.0               0.443388
10    PA     52        12986518.0               0.400415
49    DE      4         1005872.0               0.397665
37    IA     12         3195937.0               0.375477
8     NY     63        19872319.0               0.317024
22    IL     35        12692653.0               0.275750
32    MA     19         6992395.0               0.271724
28    NJ     22         9267014.0               0.237401
45    CT      6         3598348.0               0.166743
50    RI      1         1095371.0               0.091293